language: node_js
node_js:
  - 4
  - 6
  - 8

sudo: false
before_install:
  - git fetch --unshallow
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - /bin/bash lint-commits.sh
  - ./node_modules/.bin/commitlint --from=$TRAVIS_COMMIT
  - npm run tsc
  - npm test
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: pnpm/pnpm
